### PR TITLE
Check boost headers for minimal build

### PR DESCRIPTION
**Pull request by lgbaldoni**

### CODE REVIEW

**Comment by tizonia** [comment]
Hi Luigi,

Sorry, maybe I'm missing something, but do we need to check for the boost headers in a minimal build? 

This commit removed the last few boost dependencies in the minimal build:
15aec5b9b7b55f9195e9b97d155cf31e8d34e266

**Comment by lgbaldoni** [comment]
My bad. I tend to jump the gun at times.

**Comment by tizonia** [comment]
No worries, thanks a lot!

**Comment by SIN3R6Y** [comment]
Not sure if this is the best place for this... 

I'm trying to not require boost for this project, essentially i am only interested in the OpenMAX IL portion of the project to integrate with gstreamer. While i see you can disable "player", disabling play does not also disable "clients". If you aren't building the player, i don't see why "clients", "cast", or possibly even "rm" are needed.

The biggest issue is that the gmusic client also needs boost.

**Comment by tizonia** [comment]
Hi @SIN3R6Y 

Are you using the meson build system in the 'develop' branch?. You should probably read this thread #648 

In short, Tizonia has gained a new build system based on Meson. With the new build system you can do something like this:
```
meson build -Dclients=false -Dplugins='' -Dplayer=false
```
The old Autotools build system is still available but it does not allow you to remove all the non-OpenMAX IL features.

To use the Meson build, you need the 'develop' branch. It's going to be merged to master soon.
See:
https://github.com/tizonia/tizonia-openmax-il/blob/develop/BUILDING_with_meson.md

Please use #648 if you have questions about Meson.

**Pull request closed without merging**
