### PR TITLE
Added support for Ubuntu 19.04 (Disco Dingo)

### PR DESCRIPTION
**Pull request by Aldin-SXR**
- Added support for Ubuntu 19.04 (Disco Dingo), since it seems there are no major compatibility issues.

### CODE REVIEW

**Comment by tizonia** [comment]
Hi @Aldin-SXR,

First of all, thanks very much for taking the time to contribute to Tizonia. It's very much appreciated!.

I'm afraid that the change you are proposing will not work.
```
DISTRO="ubuntu" ; RELEASE="disco"
```

The reason is that RELEASE can only contain one of the versions for which there are Debian packages in Bintray, and there are no packages for Disco.
See here:
https://bintray.com/tizonia/ubuntu

Unfortunately, I can't release debian packages for every single version of Ubuntu or Debian out there; it takes too much time to produce the packages for all the different versions and architectures. Due to Tizonia's hybrid nature (C, C++, Python), I can't really use a cloud build service, so as a general rule, I'm only producing Debian packages for the last 2 LTSs of Ubuntu (i.e. Xenial, and Bionic), one Debian and one Raspbian and 2 architectures for each of them where possible. 

Debian and Ubuntu derivatives are easily supported with these debian packages when they are direct descendants (i.e. when they are binary compatible with those particular versions of Debian or Ubuntu LTS).

See:
https://github.com/tizonia/tizonia-openmax-il#debian--ubuntu--raspbian

For any other Linux distro out there that is outside of this list, the options are the Tizonia Snap package, the AUR packages (Arch and derivatives) or the Docker image.

**Comment by Aldin-SXR** [comment]
Hi, @tizonia .

I actually managed to install tizonia on my 19.04 by adding "disco" to the existing "bionic" conditional in `install.sh`, and I haven't had any issues so far.

```bash
elif echo "$RELIDS" | grep -E 'disco|bionic|juno|tara|tessa|tina'; then
```
Following this, I had assumed that simply adding a new conditional could cover it for other versions. Maybe I just got lucky with this "hack", and this isn't stable enough.

Thank you for taking the time to explain how this works in detail. It's very much appreciated.

**Comment by tizonia** [comment]
Hi @Aldin-SXR ,

```
elif echo "$RELIDS" | grep -E 'disco|bionic|juno|tara|tessa|tina'; then
  # NOTE: Elementary OS 'juno' is based on bionic
  # NOTE: Linux Mint 'tara'. 'tessa' and 'tina' are based on bionic
  DISTRO="ubuntu" ; RELEASE="bionic"
```

Actually, I assumed that this was what you did in the first place, but this is different from the change in your pull request.

Binary compatibility between 18.04 and 19.04 is not guaranteed, but most of the time binaries compiled on 18.04 will work just fine in the newer releases (the other way around would be more complicated). In fact, this is the principle in which 'universal' Snap packages operate. 

I dislike the idea though of straight adding disco to the bionic conditional since I personally have not done any testing of all the features that would be expected to work. Perhaps it would be good to somehow let users know that there is always the choice to do this 'at their own risk'. Maybe via some comment in the install.sh script or in the project README.md.

**Comment by juanrubio** [comment]
Thanks! and sorry for the delayed reply!

**Pull request merged**
