### PR TITLE
Fix build error with latest boost library

### PR DESCRIPTION
**Pull request by seferergun**

### CODE REVIEW

**Comment by juanrubio** [comment]
Hi!, thanks a lot for the PR.

It looks like this back-ward incompatible change was introduced in Boost 1.73
https://www.boost.org/users/history/version_1_73_0.html

We can't really adopt the new boost placeholder form unless we provide a solution for systems with an older version of Boost (e.g. Ubuntu 20.04 and older).

See:
- https://www.boost.org/doc/libs/master/boost/bind.hpp

Defining the below macro seems to be the alternative provided by the Boost developers for those wanting to preserve the old behaviour a little longer.
```
   BOOST_BIND_GLOBAL_PLACEHOLDER
```

Another option is always to wrap the Boost changes with an ifdef macro 
```
#if BOOST_VERSION >= 106100
#include <this.hpp>
#else
#include <that.hpp> 
#endif
```

Would you like to rework the PR with either of these?

**Comment by seferergun** [comment]
> Hi!, thanks a lot for the PR.
> 
> It looks like this back-ward incompatible change was introduced in Boost 1.73
> https://www.boost.org/users/history/version_1_73_0.html
> 
> We can't really adopt the new boost placeholder form unless we provide a solution for systems with an older version of Boost (e.g. Ubuntu 20.04 and older).
> 
> See:
> 
> * https://www.boost.org/doc/libs/master/boost/bind.hpp
> 
> Defining the below macro seems to be the alternative provided by the Boost developers for those wanting to preserve the old behaviour a little longer.
> 
> ```
>    BOOST_BIND_GLOBAL_PLACEHOLDER
> ```
> 
> Another option is always to wrap the Boost changes with an ifdef macro
> 
> ```
> #if BOOST_VERSION >= 106100
> #include <this.hpp>
> #else
> #include <that.hpp> 
> #endif
> ```
> 
> Would you like to rework the PR with either of these?

Hi,

Of course I can rework it. I might be wrong, but is it neccessary? I just added namespace prefix, it should not break on older boost libraries. On the old version it was doing:
`using namespace boost::placeholders;`
[see](https://www.boost.org/doc/libs/1_72_0/boost/bind.hpp)

by default. Now it does not. Using namespace name that has been declared with using namespace does not cause an error AFAIK.

For instance this code snippet compiles and runs perfectly:
`
#include <iostream>

using namespace std;

int main() {
  std::cout << "test" << std::endl;
  return 0;
}
`
I actually tried to build this pull request on Xubuntu 20.04 VM, and it compiled without an error(It gave me a linker error unrelated to this about boost libpython3). It would be actually great if someone confirms that it fully compiles and runs perfectly.

Am I missing something?

**Comment by faizpuru** [comment]
Waiting for this PR to be merged ! Thx for the work :clap:

**Comment by juanrubio** [comment]
@seferergun 

Thanks very much for the PR!

**Pull request merged**
