### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by CapOM**
2 minors fixes
1 debatable commit that serves as example,
1 WIP commit that requires feedback because the hook is never called.
Thx!

### CODE REVIEW

**Comment by CapOM** [comment]
Thx Juan ! Any idea why the eglimage hook is never called ? (https://github.com/tizonia/tizonia-openmax-il/blob/master/plugins/vp8_decoder/src/vp8d.c#L62)

**Comment by juanrubio** [comment]
Hi Julien, I think the hook was being called correctly, it is just that it was returning an OMX_ERRORTYPE value, instead of OMX_BOOL.

I've updated it and added some more diagnostics in tizport.c, to catch this situation easily in the future.

I'm pushing a new Skema test (Vp8DecoderEGLImage.xml) that might be useful to see this in action.

**Comment by CapOM** [comment]
Ah ok, I will re-try then maybe I missed something, the other day I added a trace and it did not show up. Thx !

**Comment by CapOM** [comment]
I found the problem and it affects only the output port. The eglimage hook is correctly registered but then it is lost because the output port is re-created or super seeded somehow. Is this normal ? Also see https://github.com/tizonia/tizonia-openmax-il/pull/347

**Comment by juanrubio** [comment]
Hi Julien,

Interesting. I think there may be a problem if a the component role is explicitely reset by the IL client. If this happens (with SetParameter(OMX_IndexParamStandardComponentRole), then the new role objects are instantiated. I.e the processor and port objects are destroyed and a new set is instantiated. And I believe in this case I forgot to re-assign the hooks. So moving the hook registration to the processor constructor actually workarounds this problem :-)

Let me have  a look, I think I can provide a fix in tizscheduler.c, to avoid having to move the hook registration call to the processor.

**Comment by CapOM** [comment]
Make sense, great, thx!

**Pull request merged**
